// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzqivkgzdcxpnotiomiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6cWl2a2d6ZGN4cG5vdGlvbWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzcwNjMsImV4cCI6MjA2NTU1MzA2M30.told0iv9CO6tx0MLGfhx5yxqWe-pd4bJI71mFdY5fYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);